### ISSUE TITLE
How do I download this?

### ISSUE THREAD

**Issue by saleem0915** [teaconmc/SlideShow#18]
How do I download this mod?

**Comment by 4wincode** [comment]
Check the releases tab: https://github.com/teaconmc/SlideShow/releases/latest

**Comment by 3TUSK** [comment]
Actually, how did you even find this? We have never officially released it, nor have we advertise it anywhere. It is public because we'd like to make it open-source.

**Comment by 4wincode** [comment]
For me, I was just looking for a online picture frame mod for 1.18.

**Comment by 3TUSK** [comment]
@4winyt 
… and then you just searched on GitHub, then landed here?

**Comment by saleem0915** [comment]
> Actually, how did you even find this? We have never officially released it, nor have we advertise it anywhere. It is public because we'd like to make it open-source.

I found it on Jonathan Ho's Top 5 best mods to use with MTR

**Comment by WindlessCarpet** [comment]
> Check the releases tab: https://github.com/teaconmc/SlideShow/releases/latest

Is there also a download link for Forge 1.16.5?

**Comment by 3TUSK** [comment]
> > Check the releases tab: https://github.com/teaconmc/SlideShow/releases/latest
> 
> Is there also a download link for Forge 1.16.5?

https://github.com/teaconmc/SlideShow/releases/tag/0.5.4 is the last version build against Minecraft 1.16.5 at the time I am writing this reply.

**Comment by WindlessCarpet** [comment]
> > > Check the releases tab: https://github.com/teaconmc/SlideShow/releases/latest
> > 
> > 
> > Is there also a download link for Forge 1.16.5?
> 
> https://github.com/teaconmc/SlideShow/releases/tag/0.5.4 is the last version build against Minecraft 1.16.5 at the time I am writing this reply.

Do I also have to download the source codes? I'm not very familiar with GitHub.
Thanks for responding

**Comment by 3TUSK** [comment]
> > > > Check the releases tab: https://github.com/teaconmc/SlideShow/releases/latest
> > > 
> > > 
> > > Is there also a download link for Forge 1.16.5?
> > 
> > 
> > https://github.com/teaconmc/SlideShow/releases/tag/0.5.4 is the last version build against Minecraft 1.16.5 at the time I am writing this reply.
> 
> Do I also have to download the source codes? I'm not very familiar with GitHub. Thanks for responding

<img width="1265" alt="Screen Shot 2022-10-07 at 1 28 53 PM" src="https://user-images.githubusercontent.com/9113033/194647637-b8188e91-4f93-461f-a3bb-d50c98958e9b.png">
