### ISSUE TITLE
Able to see banners and signs through walls when looking at a projected image

### ISSUE THREAD

**Issue by WindlessCarpet** [teaconmc/SlideShow#19]
### labeled as: **Bug**

Issue spotted on GitHub version: [https://github.com/teaconmc/SlideShow/releases/tag/0.5.4](url) 
Minecraft Java, Forge 1.16.5

When I project an image on the projector I'm able to see banners and signs through walls. Is that normal?
![2022-10-07_20 47 58](https://user-images.githubusercontent.com/108215552/194630021-38e4895b-a0a6-419a-8690-bc6ee1280bff.png)

**Comment by WindlessCarpet** [comment]
It got fixed after rejoining multiple times, still curious how it happened

**Comment by ustc-zzzz** [comment]
I'm not sure if it still happen on 1.18+ (0.6.x) and 1.19+ (0.7.x). Feel free to open the issue if the bug still occurs.
